language: node_js
node_js:
  - stable

env:
  global:
  - ENCRYPTION_LABEL: "df68496685d7"
  - COMMIT_AUTHOR_EMAIL: ci@md-systems.ch

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y calibre xvfb

script: bash ./deploy.sh
